### ISSUE TITLE
API timeout

### ISSUE THREAD

**Issue by FatKiwi** [TripleFrequency/AthamePlugin.Deezer#34]
API timeouts if you don't use app for more than 1 or 2 hours.
![snap21](https://user-images.githubusercontent.com/9163913/33806597-8e1fc904-ddc2-11e7-83e5-264953b0283d.png)

Reinitialize API after some time?

**Comment by fabriccioguzman** [comment]
this is because the API session expires for a while, it's like leaving an open paypal account for a while and the session expires

**Comment by FatKiwi** [comment]
I know that.

**Comment by TripleFrequency** [comment]
What version is this? This is fixed by 1.3A3, I believe.

**Comment by FatKiwi** [comment]
Yes, 1.3A,

**Comment by TripleFrequency** [comment]
Which alpha, is what I am asking? Is this fixed for you, or no?

**Comment by FatKiwi** [comment]
A3, sorry. A4 downloads really slow and I reverted to it.

**Comment by TripleFrequency** [comment]
So, is this fixed for you in A3?

**Comment by FatKiwi** [comment]
No, that's why I post it.

**Comment by TripleFrequency** [comment]
So I attempted to reproduce this. I left my client open for upwards of 5 hours, then attempted to add a new song. By monitoring my HTTP traffic, I could verify that my session *was* expired, and the plugin automatically obtained a new token to use.

Can you consistently reproduce this?

**Comment by FatKiwi** [comment]
No, it just throws this error. Tried a few times.

**Comment by FatKiwi** [comment]
I don't understand what is this duplicate to. If you suggest #24, that's completely different. 
Do you plan to fix the timeout bug or not?

**Comment by TripleFrequency** [comment]
I am asking if you can reproduce it. Has it happened several times? If it can't be reproduced, I can't fix it. I am saying that the issue you described matches almost perfectly with one I have already fixed in the past versions. There was never an issue created for it, because I caught the problem before anyone reported it.

One way to prove it one way or the other is as follows: wait for the error to begin occurring, sniff your http traffic (with Fiddler), watch for calls by Athame, and look at them in text view. If a call seems to say something like "VALID_CRSF_TOKEN_REQUIRED" or something like that, and the call is not followed up by a valid request (with a re-initialized client), then please tell me. If you can't do that, answering the first questions *should* suffice.

**Comment by FatKiwi** [comment]
It happened at least 3 times. I will check again, but I'm sure it becomes unusable (and throws this error) unless I reopen app.
Can't help much with Fiddler.

**Comment by TripleFrequency** [comment]
How long does it take before it throws the error? Are you saying it is just always, or consistently after a certain amount of time?

**Comment by FatKiwi** [comment]
After at least 2 hours. You need to have had deezer track entered before this time (initialize API once). If you try on hour 3 to enter new url, it will show this. I'm waiting now again and will post screenshot tomorrow.

**Comment by FatKiwi** [comment]
Result after 2 hours and 30 minutes:
![snap1](https://user-images.githubusercontent.com/9163913/33943030-bd2e212e-e00f-11e7-8358-2a7ff005d035.png)

It's definitely not fixed.

**Comment by FatKiwi** [comment]
![snap2](https://user-images.githubusercontent.com/9163913/33952075-9bf7fade-e028-11e7-9c52-344995edece6.png)

It's weird how you cannot reproduce it, when I did over 5 times. Invite other helpers and see.
the A3 plugin from 5 Dec with MD5:

**Comment by TripleFrequency** [comment]
And this request was not followed up by another request? It seems strange to me that you can reproduce it in newer versions, given [here](https://github.com/TripleFrequency/AthamePlugin.Deezer/blob/master/AthamePlugin.Deezer/Models/ModelAdapter.cs#L151) is the fix, already implemented. A fix that I have tested with this exact scenario, and works for me and others.

**Comment by TripleFrequency** [comment]
@FatKiwi I created a new release (1.3-A3.1) which should fix this issue. I would appreciate if you could test it.

**Comment by FatKiwi** [comment]
Thanks for the fix, gonna report soon.

**Comment by FatKiwi** [comment]
Works perfectly now, thanks.
